- DistFiles/localization/.guidsForInstaller.xml
- src/HearThis/HearThis.csproj
- src/HearThis/app.config
- src/HearThis/packages.config
- src/HearThisTests/HearThisTests.csproj
- src/HearThisTests/app.config
- src/HearThisTests/packages.config
- src/Installer/Installer.wxs
7.0.1 is the version SIL.WritingSystems is looking for, therefore 8.0.3 was causing a crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/4)
> Update installer and use Newtonsoft.Json 7.0.1 rather than 8.0.3 (HT-160)

- src/HearThis/HearThis.csproj
- src/HearThis/Program.cs
- src/HearThis/UI/DiscontiguousProgressTrackBar.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/ToastNotifier.cs
- src/HearThis/UI/ToastNotifier.designer.cs
- src/HearThis/UI/ToastNotifier.resx
- src/HearThis/Utils/NonFatalProblem.cs
Brought in a couple classes from Bloom that we have found helpful in dealing with these hard-to-reproduce errors. They allow us to show a "toast" that can be ignored or clicked on to send a report.
Also retrying getting brushes a couple times in case this is a timing bug. Also fall back to an all-green trackbar if even that fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/7)
> Work around and gather info on HT-9

- build/build.proj
Adding sudo -u vu2004 to the --rsync-path will cause the uploaded files to be owned by vu2004 which is the same user that would operate FTP.  This allows product teams to use a tool like Filezilla to delete old files from time to time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/8)
> Update build.proj to fix uploaded file owner

- src/HearThis/HearThis.csproj
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/RecordingToolControl.cs
Fix RTL for line splitting dialog. Remove ICSharp as it is no longer used (replaced by Ionic.ZIP).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/2)
> RTL Fixes - RecordInParts Dialog

- src/HearThis/UI/DiscontiguousProgressTrackBar.cs
- src/HearThis/UI/RecordingToolControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThisTests/DiscontiguousProgressTrackBarTests.cs
Per JohnT's suggestion in the PR for HT-9, I have reworked the way GetSegmentBrushes and SegmentCount interact so that the responsibility for keeping them in synch lies squarely with a single class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/10)
> Made RecordingToolControl solely responsible for ensuring that GetSegmentBrushes returns SegmentCount brushes

- DistFiles/ReleaseNotes.md
- src/HearThis/UI/Shell.cs
- src/Installer/appcast.xml
HT-188: Changed appcast.xml for 1.5 branch to look for the latest version in the 1.5 and the code to look for the appcast.xml file from the latest successful 1.5 build.
HT-190: Updated the link URL in appcast.XML to point to software.sil.org/hearthis/download
HT-191: Updated release notes to indicate support for Paratext 8 projects and distinguish between HT 1.4.x and 1.5.x.
HT-192: Updated the enclosure URL (to access the latest msi) in appcast.XML to include the /r folder so we don't get a 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/13)
> HT-187: Fixed bugs related to the "Sparkle" code to get the latest version of HT 1.5

- DistFiles/ReleaseNotes.md
- src/Installer/appcast.xml
HT-190: Updated the link URL in appcast.XML to point to software.silorg/hearthis/download
HT-191: Updated release notes to indicate support for Paratext 8 projects and distinguish between HT 1.4.x and 1.5.x.
HT-192: Updated the enclosure URL (to access the latest msi) in appcast.XML to include the /r folder so we don't get a 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/14)
> HT-187: Fixed 404 (URL not found) trying to access HT 1.4 upgrades

- .gitignore
- DistFiles/ReleaseNotes.md
- build/getDependencies-windows.sh
- src/HearThis/HearThis.csproj
- src/HearThis/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/19)
> HT 201: Switch from NuGet's version of NetSparkle to the SILLsDev version, which fails quietly if not connected to the Internet.

- build/getDependencies-windows.sh
- build/readme - making getDependencies script.txt
- src/HearThis/Program.cs
- src/HearThis/UI/ChooseProject.cs
Updated dependencies script (and dependencies on TC) to peg to an older version of libpalaso that has a version of icu.net.dll that is compatible with Paratext 8.
Also, changed check and corresponding message to tell user about using an earlier version of HT if PT7 is installed.
DO NOT MERGE THIS CHANGE INTO the 1.4 branch!!!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/20)
> HT-206: Made HT 1.5 branch work with Paratext 8

- src/HearThis/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/50)
> Load Paratext projects even when first loading a multivoice script (HT-221)

- src/HearThis/UI/ActorCharacterChooser.cs
- src/HearThis/UI/Shell.cs
???? remains at startup in overview mode
Large size of ???? is removed.
Fix temporary display of "Character" at startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/60)
> Show Overview when user selects that

- src/HearThis/HearThis.csproj
- src/HearThis/Program.cs
- src/HearThis/Properties/Settings.Designer.cs
- src/HearThis/Properties/Settings.settings
- src/HearThis/Publishing/PublishDialog.cs
- src/HearThis/Publishing/PublishingModel.cs
- src/HearThis/Script/IPublishingInfoProvider.cs
- src/HearThis/Script/IScrProjectSettingsProvider.cs
- src/HearThis/Script/MultiVoiceScriptProvider.cs
- src/HearThis/Script/ParatextParagraph.cs
- src/HearThis/Script/ParatextScriptProvider.cs
- src/HearThis/Script/Project.cs
- src/HearThis/Script/ProjectSettings.cs
- src/HearThis/Script/ScriptProviderBase.cs
- src/HearThis/UI/AdministrativeSettings.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/ScriptControl.cs
- src/HearThis/UI/Shell.cs
- src/HearThis/app.config
- src/HearThisTests/ClipRepositoryTests.cs
- src/HearThisTests/ParatextParagraphTests.cs
- src/HearThisTests/ParatextScriptProviderTests.cs
- src/HearThisTests/ProjectTests.cs
- src/HearThisTests/SentenceClauseSplitterTests.cs
BreakQuotesIntoBlocks, ClauseBreakCharacters, AdditionalBlockBreakCharacters
Also fixed a couple minor typos and handled cleanly the (unlikely and as yet never encountered, AFAIK) case where a project settings file has become corrupted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/93)
> HT 254: Migrate some settings from user settings to project-specific settings

- src/HearThis/Script/ParatextParagraph.cs
- src/HearThisTests/ParatextParagraphTests.cs
This only happens when the project does not have all quote levels filled in and the text contains some < and > symbols and the first-level quotes are not << and >>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/95)
> HT-260: Fix index out-of-range crash when replacing chevrons with quotes

- DistFiles/localization/HearThis.es.tmx
- src/HearThis/Program.cs
- src/HearThis/UI/ChooseProject.cs
In case where ParatextData.ScrTextCollection is unable to successfully set the folder the user provides as the location where it should find Paratext project data. This does not exactly fix the problem reported in this issue, but it should make it possible for the Paratext developers to see the call stack and thus rectify the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/100)
> HT-240: Improved error reporting when manually setting P8 project location

- src/HearThis/Publishing/ClipRepository.cs
- src/HearThisTests/ClipRepositoryTests.cs
To do this, I reset the variable that accumulates total time for verses represented by multiple clips each time a line is appended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/110)
> HT-200: Prevent overlapping timings in generated Audacity label file

- DistFiles/localization/HearThis.es.tmx
- src/HearThis/Publishing/PublishDialog.cs
- src/HearThis/UI/Shell.cs
HT-290: Keep Export button enabled when user changes destination folder.
HT-264, HT-215: Updated message that user sees when the Save button is clicked so that it accurately reflects current UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/111)
> UI Improvements to Export

- Copy Libaries.bat
- src/HearThis/Communication/AndroidSynchronization.cs
- src/HearThis/Communication/WindowsLink.cs
- src/HearThis/Program.cs
- src/HearThis/Publishing/AudiBibleEncoder.cs
- src/HearThis/Publishing/BunchOfFilesPublishingMethod.cs
- src/HearThis/Publishing/ClipRepository.cs
- src/HearThis/Publishing/FlacEncoder.cs
- src/HearThis/Publishing/LameEncoder.cs
- src/HearThis/Publishing/OggEncoder.cs
- src/HearThis/Publishing/PublishingMethodBase.cs
- src/HearThis/Publishing/WavEncoder.cs
- src/HearThis/Script/BibleStats.cs
- src/HearThis/Script/ChapterInfo.cs
- src/HearThis/UI/AudioButtonsControl.cs
- src/HearThis/UI/MergeProgressDialog.cs
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/Shell.cs
- src/HearThis/UI/TextBundleScripture.cs
- src/HearThis/Utils/Utils.cs
Duplicate bug reports: HT-292, HT-293
Also:
Replaced calls to File.Copy, File.Delete, File.Move, and File.Write... with corresponding RobustFile versions.
Replaced deprecated uses of FileLocator class.
Improved two error messages and made them localizable.
Other minor code cleanup.
Made CopyFiles batch file more flexible (now able to pull libpalaso DLLs from either debug or DebugStrongName)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/112)
> HT-265: Fixed bug: File.Copy failed because it couldn't overwrite file when doing Android synch.

- src/HearThis/Utils/Utils.cs
Since both existing callers pass true and I implemented it with the assumption that it was true, there's no functional problem in HearThis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/113)
> Fixed new Move method to actually take into consideration the overwrite parameter.

- DistFiles/ReleaseNotes.md
- src/HearThis/UI/AppPallette.cs
- src/HearThis/UI/AudioButtonsControl.Designer.cs
- src/HearThis/UI/AudioButtonsControl.cs
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/Shell.cs
HT-334: Re-implemented contrasting colors for part 1 and part 2 highlights in "Record in Parts" dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/126)
> Fixed regression bug and performance problem in "Record in Parts" dialog

- DistFiles/localization/HearThis.es.tmx
- DistFiles/localization/HearThis.fr.tmx
- src/HearThis/UI/AudioButtonsControl.cs
- src/HearThis/UI/CustomButton.cs
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/RecordingToolControl.cs
Rather than raising the SoundFileCreated event immediately after telling the Recorder to Stop and then waiting 200 ms after that event to attempt to write the combined audio, wait to raise the event until after the recorder is actually back in the Monitoring state (after going through the RequestedStop state).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/131)
> HT-338, HT-339: Prevent truncation of combined audio (part 2 omitted). Prevent crash for short recording.

- DistFiles/ReleaseNotes.md
- src/HearThis/UI/AppPallette.cs
- src/HearThis/UI/AudioButtonsControl.Designer.cs
- src/HearThis/UI/AudioButtonsControl.cs
- src/HearThis/UI/CustomButton.cs
- src/HearThis/UI/RecordInPartsDlg.Designer.cs
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/RecordInPartsDlg.resx
- src/HearThis/UI/RecordingToolControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/ScriptControl.cs
- src/HearThisTests/ScriptLinePainterTests.cs
This makes it nearly invisible so that the reader can't accidentally read the wrong thing.
Noticed that there was code to try to brighten the context when mouse goes over the script, so re-enabled that. However, the difference is very minimal and this may have been removed on purpose.
Also, did some cleanup to remove some unused code related to AppPalette and the ScriptControlPainter.
This change was motivated by:
https://community.scripture.software.sil.org/t/hearthis-to-sab-sound-file-misalignment/1171/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/133)
> During recording, the script "context" text is muted

- DistFiles/localization/.guidsForInstaller.xml
- src/Installer/Installer.wxs
Changed Installer to require .Net Framework 4.6.1
Also added installer GUIDs for Palaso localization files
WIP: Use redistributable C++ runtime instead of having the file checked into source and installed with HearThis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/137)
> Installer improvments

- src/HearThis/UI/DiscontiguousProgressTrackBar.cs
This was in response to https://trello.com/c/pUDbOMOq/240-sometimes-its-difficult-to-see-the-different-segments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/155)
> Increase gap width slightly when segments are wide.

- src/HearThis/UI/DiscontiguousProgressTrackBar.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/ScriptTextHasChangedControl.cs
- src/HearThis/UI/UnitNavigationButton.cs
This is a different approach to trying to get exclamation marks that are more visible. It definitely yields heavier, more noticeable exclamation marks, but depending on the size, the dithering isn't always optimal. Maybe I need to try drawing the entire top portion as a single polygon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/156)
> HT-359: Paint custom heavy exclamation marks instead of drawing as strings

- src/HearThis/Program.cs
- src/HearThis/UI/Shell.cs
- src/Installer/Bootstrapper/HearThis Bootstrap Installer.wxs
Sadly, this required a hack.
Also reverted to showing release notes only when launched from Installer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/163)
> HT-370 (part 2): Make HearThis the active app when launched from bootstrapper

- src/Installer/Installer.wxs
Since this is included in .Net Framework 4.7 and later and this version of HearThis targets 4.7.2, it is not needed.
This reverts commit cdcf835c15a607f2ef61c9e14d84d319475883a5, reversing
changes made to b0e79d4028d66986d65e9c018414176a7bc2f849.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/167)
> HT-371: Revert inclusion of System.ValueTuple.dll in Installer

- src/HearThis/Communication/AndroidSynchronization.cs
- src/HearThis/Program.cs
- src/HearThis/Script/ScriptProviderBase.cs
- src/HearThis/UI/RecordInPartsDlg.cs
- src/HearThis/UI/Shell.Designer.cs
- src/HearThis/UI/Shell.cs
- src/HearThis/UI/UpgradeNeededDialog.cs
Logging was previously used minimally but never properly initialized.
Added Logger calls to try to get more info about HT-398
Added MenuDropDownOpening to ensure dropdown menus display on correct screen
Fixed some type case typos in identifiers
Made Android Sync window appear on same screen as HearThis main window.
Added using for use of SaveFileDialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/188)
> Added logging and other minor enhancements

- DistFiles/localization/HearThis.es.xlf
- DistFiles/localization/HearThis.fr.xlf
- DistFiles/localization/HearThis.pt.xlf
- HearThis.sln.DotSettings
- src/HearThis/Publishing/PublishingModel.cs
- src/HearThis/UI/AudioButtonsControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.cs
Fixed misleading plural in one of the tool tips in English.
Fixed error in one of the Spanish tool tips.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/204)
> Internationalization bug fixes + minor UI improvements

- DistFiles/localization/HearThis.es.xlf
- DistFiles/localization/HearThis.fr.xlf
- DistFiles/localization/HearThis.pt.xlf
- src/HearThis/UI/AudioButtonsControl.cs
- src/HearThis/UI/RecordInPartsDlg.cs
I'm thinking that having the joined file open might be the cause of the occasional corrupt (0-byte) file we've seen reported from the field (e.g., HT-342)
HT-341: Improved wording of error message to make it possible to provide better support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/208)
> Prevent continued playback of files in RecordInPartsDlg once dialog is closed

- src/HearThis/Script/ChapterInfo.cs
We should not be passing the _scriptProvider in this call to GetPathToLineRecording because the line number is calculated based on the passed-in selectedScriptBlock, whose Number already correctly reflects the place in the unfiltered sequence of blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/213)
> Fixed bug in OnScriptBlockRecorded for glyssenscript-based projects.

- src/HearThis/Program.cs
- src/HearThis/Properties/Settings.Designer.cs
- src/HearThis/Properties/Settings.settings
- src/HearThis/UI/AdministrativeSettings.cs
- src/HearThis/app.config
This allows the shift clips feature to be turned on (and remain enabled) when changing the color scheme. (It will also make it easier to know when to do or not do other things in response to this kind of special restart.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/214)
> Improved the way we track whether a restart was in response to a color scheme change

- src/HearThis/Program.cs
I'm really mystified as to why/how the .* was ever added. We only put it on one of the two. Looking at the code in L10nSharp (see line 194 in StringExtractor.cs), I can't see how .* could ever have worked, and that code is essentially the same as it has been for at least 10 years. Oddly, I couldn't detect any difference between having and not having it, but I suspect that is because it just uses the checked-in version of the English xlf file rather than (or in addition to) scanning for new strings, and maybe (I guess) our checked in file has all the strings from those two namespaces.
Note that Glyssen also had this. See [similar PR for Glyssen](https://github.com/sillsdev/Glyssen/pull/818).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Removed .* from end of namespace spec in call to LocalizationManage.Create

- src/HearThis/UI/RecordingToolControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/Shell.cs
This approach also improves encapsulation, as the Shell does not need to know about RecordInParts role as a message filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/227)
> Prevented multiple instances of Record In Parts dialog

- src/HearThis/Script/ShiftClipsViewModel.cs
- src/HearThis/UI/ShiftClipsDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/228)
> HT-429: Prevent crash in ShiftClipsDlg caused by an ill-constructed model

- src/HearThis/Script/Project.cs
- src/HearThis/Script/ShiftClipsViewModel.cs
HT-430: This might not be the final solution, but for now, when looking for shiftable blocks, stop when we hit a skipped block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/231)
> HT-429: Prevent InvalidOperationException in CheckForProblems mode

- src/HearThis/Script/Project.cs
- src/HearThis/UI/RecordingToolControl.Designer.cs
- src/HearThis/UI/RecordingToolControl.cs
Prevent showing shift clips menu for chapter with only one block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/232)
> Re-instated tool tip to help user deal with extra clips.

- src/HearThis/HearThis.csproj
- src/HearThis/Program.cs
- src/HearThis/Utils/StringDifferences/StringDifferenceFinder.cs
- src/HearThisTests/HearThisTests.csproj
- src/HearThisTests/Utils/StringDifferences/StringDifferenceFinderTests.cs
- src/Installer/Installer.wxs
Upgrade to latest ICU (v. 13 of Unicode) and libpalaso libraries to get improved behavior in StringDifferenceFinder
Fixed bugs in StringDifferenceFinder related to handling of surrogate pairs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/242)
> StringDifferenceFinder improvements

- src/HearThis/Script/HearThisPackMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/245)
> HT-259: Set UseZip64WhenSaving to allow HearThis packs that exceed 32-bit limits

- DistFiles/localization/HearThis.id.xlf
Needed to be distinct from the terms used in Oral Bible Translation for "set" and "passage".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/256)
> Changed the Indonesian term for "block"

- src/HearThis/UI/Shell.cs
There is a slight chance and existing project could have a previously created XML report, so we need to look for that as well and alert the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/265)
> HT-456: Look for old XML-style report and alert user

- src/HearThis/UI/ScriptTextHasChangedControl.cs
1) Going from a block that shows a difference between then and now to a block with no recording info (recorded with an older version of HearThis).
2) Selecting a block that was previously marked as being OK following a minor text change, but then the text is changed again, such that the recording needs to be re-evaluated.
Note: I found these two problems while looking at HT-461, but I'm not very sure that either of these is actually related to the originally reported bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/267)
> Fixed the display/behavior of Check for Problems view in two cases

- src/HearThis/Script/ChapterInfo.cs
- src/HearThis/Script/Project.cs
(because the text was reverted to match the way it was when the clip was originally recorded).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/268)
> HT-461: Prevent showing an exclamation for a segment that has no actual problem

- src/HearThis/Script/ChapterInfo.cs
- src/HearThisTests/ChapterInfoTests.cs
Only count skips toward percentage that a chapter is recorded if something has been recorded or everything is skipped
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/277)
> HT-193: Prevent reporting partially complete chapters when blocks are merely skipped

- src/HearThis/UI/ScriptControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/278)
> HT-230: If script font is missing on computer, use fallback instead of crashing

- src/HearThis/Publishing/ClipRepository.cs
- src/HearThis/Script/ScriptProviderBase.cs
- src/HearThisTests/ClipRepositoryTests.cs
- src/HearThisTests/TestErrorReporter.cs
1. Deal with possibility of both a skip and clip file existing for a particular block.
2. Avoid renaming skip files back to wav files (clips) for blocks that were explicitly skipped, then had their style skipped, and then have their style unskipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/274)
> HT-465: Handle edge cases with skip/clip files and prevent crash when both unexpectedly exist

- DistFiles/ReleaseNotes.md
- build/build.proj
- src/HearThis/UI/ChooseProject.cs
- src/Installer/template.download_info
Changed build to no longer create download info files with specific Paratext version references. Changed specific references to Paratext 8 in ReleaseNotes to also include later versions. Removed potentially confusing references to Paratext 7 (no longer supported) from ReleaseNotes. Changed logic in Find Paratext Projects Folder dialog to try to find any of the "standard" Paratext Project locations that might exist to use as default location
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/290)
> Make improvements related to Paratext versioning:

- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/Shell.cs
This prevents a crash when "Record long lines in parts" button is showing but there is no current script line
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/311)
> HT-489: Hide "Record long lines in parts" button at end of chapter

- src/HearThisTests/app.config
These unnecessary binding redirects seem to cause test failures for some developers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/314)
> Removed unnecessary binding redirects for System DLLs from test app.config file

- src/HearThis/Publishing/ClipRepository.cs
- src/HearThis/Script/ChapterInfo.cs
- src/HearThis/Script/ChapterRecordingInfoBase.cs
- src/HearThis/Script/InvalidFileException.cs
- src/HearThis/Script/Project.cs
- src/HearThis/UI/MouseSensitiveIconButton.cs
- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/ScriptTextHasChangedControl.cs
- src/HearThisTests/ChapterInfoTests.cs
- src/HearThisTests/ClipRepositoryTests.cs
- src/HearThisTests/ScriptProviderBaseTests.cs
- src/HearThisTests/TestErrorReporter.cs
Made handling of corrupt/missing files more robust.
Fixed several other minor errors in Check for Problems mode (e.g., displaying different for extra blocks).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/320)
> HT-496: Prevented incorrect "Cannot check validity of nonexistent file" scenario

- src/HearThis/Script/Project.cs
This could happen in a GlyssenScript project when using Shift Clips because we used the unfiltered block index to reference a block in a filtered collection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/322)
> HT-495: Prevent IndexOutOfRangeException

- src/HearThis/UI/RecordingToolControl.cs
- src/HearThis/UI/Shell.cs
What I'd really like to do is figure out how this can ever happen, but for now, I'd like to at least keep it from crashing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/330)
> HT-504, HT-133, HT-281: Prevent crashes when project is null

- DistFiles/ReleaseNotes.md
- src/HearThis/Communication/AndroidSynchronization.cs
When advertising its local IP address in a QR code, HearThis (HT) can sometimes show the wrong address. This is because it decides to use the wrong network interface. I observed this in my home setup three months ago. Windows 10 chose to use a virtual interface associated with my machine's VPN tunnel, and the tunnel's IP address got baked into the QR code for HearThisAndroid (HTA) to scan. This local IP address lived on a different subnet, which HTA's UDP response could not reach. Thus the desired HT/HTA connection and sync never occurred.
This changeset addresses the issue by determining the local IP in very similar fashion to a PR submitted yesterday for BloomDesktop. The sequence goes like this:
A) Examine the machine's network interfaces. Note that there could be several of these - my …
> Fix incorrect local IP address sometimes put in QR code
