src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/5)

Prevent a crash during close of the application

---

src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/HearThis.csproj
src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Properties/Settings.settings
src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ProjectSettings.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs
src/HearThis/app.config
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/ScriptProviderBaseTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/15)

Add option to break at all paragraph breaks or not (HT-185)

---

src/HearThis/HearThis.csproj
src/HearThis/Program.cs
src/HearThis/Script/BibleStats.cs
src/HearThis/Script/MultiVoiceBlock.cs
src/HearThis/Script/MultiVoiceBook.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/MultiVoiceScriptProviderTests.cs

With this change, if HearThis is passed a glyssenscript as a command line argument, it will open it and allow recordings to be made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/23)

Make HearThis handle MultiVoice scripts

---

src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Script/BookInfo.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/IActorAssignmentsProvider.cs
src/HearThis/Script/IScriptProvider.cs
src/HearThis/Script/MultiVoiceBook.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/ClipRepositoryCharacterFilterTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/26)

Get basic filtering working

---

src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs

--to make room for new ones (added but not implemented yet)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/27)

Convert several toolbar buttons to menu items

---

src/HearThis/Script/IActorAssignmentsProvider.cs
src/HearThis/Script/ScriptLine.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThisTests/ChapterInfoTests.cs
src/HearThisTests/ClipRepositoryCharacterFilterTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/28)

Record actor, character, and time of recordings

---

src/HearThis/Communication/WindowsLink.cs
src/HearThis/HearThis.csproj
src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/HearThisPackMaker.cs
src/HearThis/Script/HearThisPackReader.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/RepoMerger.cs
src/HearThis/UI/MergeProgressDialog.Designer.cs
src/HearThis/UI/MergeProgressDialog.cs
src/HearThis/UI/MergeProgressDialog.resx
src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/HearThisPackMakerTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/RepoMergerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/29)

Create and merge HearThisPack files for sharing audio

---

src/HearThis/UI/ActorCharacterChooser.Designer.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/Shell.cs

Way to turn off character filter; fix bugs changing project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/31)

Some cleanup

---

src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs

(Takes user to https://community.scripture.software.sil.org/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/33)

Add Support command

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/IScriptProvider.cs
src/HearThis/Script/MultiVoiceBook.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThisTests/ClipRepositoryCharacterFilterTests.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/32)

Show Introduction block even if empty for character

---

src/HearThis/UI/ActorCharacterChooser.Designer.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

(Replaces the old 'Show all passages' button)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/34)

Introduce 'Overview' as first actor

---

src/HearThis/Script/HearThisPackMaker.cs
src/HearThis/UI/MergeProgressDialog.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/HearThisPackMakerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/35)

Provide progress dialog for making HearThisPack

---

src/HearThis/UI/ActorCharacterChooser.Designer.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/ActorCharacterChooser.resx
src/HearThis/UI/MergeProgressDialog.Designer.cs
src/HearThis/UI/MergeProgressDialog.resx
src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/36)

Internationalize Multivoice stuff

---

src/HearThis/HearThis.csproj
src/HearThis/Script/GenericScriptureSettings.cs
src/HearThis/Script/MultiVoiceBlock.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/ScriptLine.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/39)

Break up Glyssen Blocks into lines

---

src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/ChooseProject.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/40)

Make a link to open GlyssenScript from choose project dialog

---

src/HearThis/UI/RecordingToolControl.Designer.cs

Looks much more complicated than it is thanks to designer. All I really did was reduce the top margin on the books flow from 3px to zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/41)

Reduce book label margin to match chapter

---

src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/42)

Adjust minimum size to prevent peak meter overlapping record button

---

src/HearThis/Script/Project.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/43)

Show translated blocks as recordable in progress in overview

---

src/HearThis/UI/ToolStripColorArrowRenderer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/46)

Improve menu item coloring

---

src/HearThis/Script/MultiVoiceBook.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/UI/DiscontiguousProgressTrackBar.cs

Also fixes a problem with rendering them,,,but manual skips are not yet persisted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/47)

Make skip button work in multivoice

---

src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/45)

Update the UI appropriately after a merge

---

src/HearThis/Script/MultiVoiceScriptProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/48)

Fix persistence of skip info for multi-voice

---

src/HearThis/Script/MultiVoiceScriptProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/44)

Check version number of glyssen script files

---

build/getDependencies-windows.sh
src/HearThis/HearThis.csproj
src/HearThis/packages.config
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/52)

Fix loading of Paratext projects by getting icu dependencies via NuGet (HT-221)

---

src/HearThis/UI/SentenceClauseSplitter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/53)

HT-221 Handle project settings with empty quote strings

---

src/HearThis/HearThis.csproj
src/HearThis/Publishing/IRecordingAvailability.cs
src/HearThis/RecordingAvailability.cs
src/HearThis/Script/IActorAssignmentsProvider.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/Project.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThisTests/ClipRepositoryCharacterFilterTests.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/56)

Select first unrecorded block for character on select chapter

---

src/HearThis/UI/ScriptControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/58)

Show character labels just above each text line

---

src/HearThis/HearThis.csproj
src/HearThis/UI/SaveHearThisPackDlg.Designer.cs
src/HearThis/UI/SaveHearThisPackDlg.cs
src/HearThis/UI/SaveHearThisPackDlg.resx
src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/59)

Use a dialog to explain HearThisPack and hold actor control

---

.gitignore
DistFiles/aboutBox.htm
DistFiles/aboutbox.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/61)

Clean up about box

---

src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/62)

Fix a crash when looking for first unrecorded chapter in missing book

---

src/HearThis/UI/DiscontiguousProgressTrackBar.cs
src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/63)

Separate the blocks in the progress bar

---

src/HearThis/UI/ActorCharacterChooser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/67)

Fix back color of list boxes (and highlight color)

---

src/HearThis/UI/ToolStripColorArrowRenderer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/66)

Make separators in More menu visible

---

src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/65)

Restore hiding the skip button

---

src/HearThis/Script/MultiVoiceScriptProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/68)

Fix data model for right-to-left

---

src/HearThis/UI/ScriptControl.cs
src/HearThis/UI/Shell.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/69)

Fix some line spacing problems

---

src/HearThis/UI/ActorCharacterChooser.Designer.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/ActorCharacterChooser.resx
src/HearThis/UI/BookButton.cs
src/HearThis/UI/ChapterButton.cs
src/HearThis/UI/Shell.Designer.cs

Different check mark
Larger font in choose dialog (mainly for checkmark)
Ellipsis added to some menu items
Even sides on selection rectangles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/70)

Various UI cleanup

---

src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/71)

Initialize break-at-commas button

---

src/HearThis/Script/MultiVoiceChapter.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/72)

Update based on changes to the xml naming

---

src/HearThis/Program.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/73)

Get the project name from some attributes that can't be missing

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
LICENSE.txt
src/HearThis/Properties/AssemblyInfo.cs
src/HearThis/Script/IScrParserState.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/ParserState.cs
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ParserStateStub.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/74)

HT-233: Fixed bug to add support for transliterated text (in \tl field).

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
LICENSE.txt
src/HearThis/Properties/AssemblyInfo.cs
src/HearThis/Script/IScrParserState.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/ParserState.cs
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ParserStateStub.cs

(Cherry-picked from master)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/75)

HT-233: Fixed bug to add support for transliterated text (in \tl field)

---

.nuget/NuGet.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/78)

Updated URL for getting nuget.exe

---

build/build.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/80)

Added task for Nunit3

---

build/build.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/81)

Added back in the definition of TestAssemblies that I deleted by mistake

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/83)

Fixed one more spot in the Installer.

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/84)

Added missing DLL (PtxUtils) to Installer.

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/86)

And now with new and improved correct syntax!

---

DistFiles/.guidsForInstaller.xml
build/getDependencies-windows.sh
src/HearThis/HearThis.csproj
src/HearThis/app.config
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/87)

Fixed Installer and binding redirect problems yet again in another way.

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/89)

Fixed problem with filenames in Installer.wxs

---

build/getDependencies-windows.sh
src/Installer/Installer.wxs

(No longer in libpalaso and apparently/hopefully not needed by NetSparkle.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/90)

Removed ionic.zip from installer.

---

src/HearThis/Publishing/PublishDialog.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/SentenceClauseSplitter.cs
src/HearThisTests/HearThisTests.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/91)

Fixed HT-249, HT-250 (duplicate), and HT-251

---

DistFiles/localization/HearThis.es.tmx
src/HearThis/Publishing/PublishDialog.Designer.cs
src/HearThis/Publishing/PublishDialog.resx
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.resx
src/HearThis/UI/RecordInPartsDlg.Designer.cs
src/HearThis/UI/RecordInPartsDlg.resx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/94)

HT-135: Solved internationalization problems and updated Spanish localization

---

DistFiles/ReleaseNotes.md
src/HearThis/HearThis.csproj
src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Properties/Settings.settings
src/HearThis/Script/BookInfo.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/Project.cs
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/AppPallette.cs
src/HearThis/UI/BookButton.cs
src/HearThis/UI/ChapterButton.Designer.cs
src/HearThis/UI/ChapterButton.cs
src/HearThis/UI/RecordingToolControl.Designer.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/ScriptControl.cs
src/HearThis/UI/Shell.Designer.cs
src/HearThis/UI/Shell.cs
src/HearThis/UI/UnitNavigationButton.cs
src/HearThis/app.config

This PR also includes a few minor bug fixes related to UI state inconsistencies and a tiny bit of general code cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/96)

HT-257 (dup: HT-250): Added option to display book/chapter labels on buttons.

---

src/HearThis/Script/ProjectSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/97)

Fix crash when project settings do not deserialize properly (HT-268)

---

src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/UI/AndroidSyncDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/98)

HT-243 Handle exceptions better on Android sync

---

.gitignore
build/getDependencies-windows.sh
src/HearThis/Publishing/LameEncoder.cs
src/HearThis/Publishing/PublishDialog.Designer.cs
src/HearThis/Publishing/PublishDialog.cs
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/101)

HT-275: Removed links to download LAME and made it part of basic installation.

---

src/HearThis/Publishing/ClipRepository.cs
src/HearThisTests/ClipRepositoryTests.cs

when publishing or calculating recording stats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/105)

HT-229: Ignore non-numeric folders in book folder & non-numeric wav files in chapter folder

---

.gitignore
src/HearThis/Publishing/ClipRepository.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/HearThisTests.csproj

when publishing or calculating recording stats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/106)

HT-229 (for v 1.4): Ignore non-numeric folders in book folder & non-numeric wav files in chapter folder

---

src/HearThis/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/107)

Initialize SLDR (otherwise, an error can be thrown while opening DBL bundle)

---

src/HearThis/Publishing/PublishDialog.cs

Instead "foobar", which is a Designer placeholder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/109)

Fixed the display of the output folder when the publish dialog appears initially

---

.nuget/NuGet.targets
src/HearThis/Program.cs
src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Properties/Settings.settings
src/HearThis/Script/ParatextProjectProxy.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/app.config

Also, some misc cleanup, fixing typos, refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/114)

HT-307: Fixed problem of not initializing the SLDR when Paratext is not installed

---

.nuget/NuGet.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/115)

Another change to NuGet.targets to prevent failure when restoring packages on CI build

---

.nuget/NuGet.targets
build/getDependencies-windows.sh
src/HearThis/HearThis.csproj
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/116)

Fix build problems related to NuGet

---

DistFiles/localization/HearThis.es.tmx
DistFiles/localization/HearThis.fr.tmx
DistFiles/localization/Palaso.es.tmx
src/HearThis/Program.cs
src/HearThis/Publishing/AudiBibleEncoder.cs
src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Publishing/FlacEncoder.cs
src/HearThis/Publishing/LameEncoder.cs
src/HearThis/Publishing/OggEncoder.cs
src/HearThis/Publishing/PublishDialog.Designer.cs
src/HearThis/Publishing/PublishDialog.cs
src/HearThis/Script/SampleScriptProvider.cs
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/RecordingToolControl.Designer.cs
src/HearThis/UI/Shell.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/117)

Localization improvements (+ French)

---

DistFiles/localization/HearThis.es.tmx
DistFiles/localization/HearThis.fr.tmx
DistFiles/localization/Palaso.es.tmx
DistFiles/localization/Palaso.fr.tmx
src/HearThis/Program.cs
src/HearThis/Publishing/PublishDialog.Designer.cs
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/RecordInPartsDlg.Designer.cs
src/HearThis/UI/SaveHearThisPackDlg.Designer.cs
src/HearThis/UI/Shell.cs
src/HearThis/UI/UpgradeNeededDialog.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/118)

HT-312 French palaso strings & other localization improvements

---

build/getDependencies-windows.sh
src/HearThis/HearThis.csproj
src/HearThis/UI/TextBundleScripture.cs
src/HearThis/app.config
src/HearThis/packages.config
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/app.config
src/HearThisTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/119)

Upgraded to ParatextData 9.0.1

---

DistFiles/localization/HearThis.fr.tmx
DistFiles/localization/Palaso.fr.tmx

plus fixed/added a few others
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/121)

HT-312: Added About & Publish Dialog French strings

---

DistFiles/localization/Palaso.es.tmx
DistFiles/localization/Palaso.fr.tmx
src/HearThis/Program.cs
src/HearThis/UI/Shell.cs
src/HearThis/app.config

(Depends on libpalaso PR 789)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/120)

Improvements to HearThis Settings Protection password notice

---

src/HearThis/Program.cs

I can't reproduce the problem, so I don't know if this will help, but it seems to be a more reliable check and it slightly simplifies the code in HearThis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/123)

HT-320: Attempt to prevent "The SLDR has already been initialized"

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Properties/Settings.settings
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/app.config

Also updated aboutBox.htm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/124)

HT-322: Increased maximum clip recording length from 1 minute to 10.

---

src/HearThis/Script/ParatextScriptProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/125)

HT-332: Added support for embedded glossary entries (\+w)

---

src/HearThis/Program.cs

Fix for https://community.scripture.software.sil.org/t/stop-apologizing/1078
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/127)

Remember initial UI language choice when default UI language is not available

---

src/HearThis/HearThis.csproj
src/HearThis/Program.cs
src/HearThis/UI/AlertImpl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/129)

Set implementation of Alert so Paratext load errors can be displayed.

---

ReadMe.md

Make a few Readme tweaks to get started with Visual Studio 2019 and run tests
This is based upon my own experience cloning the repo, building and running tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/135)

Update Readme for VS 2019

---

HearThis.sln.DotSettings
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/Shell.cs

This was at Bryan's request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/136)

Added Analytics events to track usage of HearThis for different types of projects

---

build/build.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/138)

Added steps to SignInstaller target to fix signing problem

---

HearThis.sln.DotSettings
ReadMe.md
src/HearThis/Program.cs
src/HearThis/UI/AudioButtonsControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/139)

HT_357: Prevent null reference exception

---

src/Installer/Bootstrapper/HearThis Bootstrap Installer.wxs

This is apparently what irrKlamg 64-bit really wants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/140)

Changed from the 2015 redistributable to the 2013 version

---

DistFiles/ReleaseNotes.md
DistFiles/localization/HearThis.es.tmx
ReadMe.md
src/HearThis/Program.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/CustomButton.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs
src/Installer/appcast.xml

Removed some info from readme about LAME that is no longer relevant
Changed http: to https: in several source files and localization comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/141)

Fixed the URL to the installer in appcast

---

build/build.proj
src/HearThis/HearThis.csproj
src/HearThis/Program.cs
src/HearThis/Properties/AssemblyInfo.cs
src/HearThis/packages.config
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/Properties/AssemblyInfo.cs
src/HearThisTests/packages.config

Bumped up to the latest NUnit ConsoleRunner.
Minor code cleanup/tweaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/142)

Updated to get the version of the SIL logo with the Registered trademark.

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThisTests/RepoMergerTests.cs

For background, see https://github.com/sillsdev/bible-karaoke/issues/41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/143)

Fixed clip-shifting feature to also fix up info.xml file

---

build/build.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/145)

Removed Upload target and the part of MakeDownloadPointers that did the rsync

---

src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/149)

HT-365: Forced initial display update to prevent bug when 4th block is initial selection

---

build/build.proj
src/Installer/Bootstrapper/HearThis Bootstrap Installer.wixproj
src/Installer/Installer.wixproj

This mimics a similar change in Glyssen a couple months ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/151)

Moved signing details from proj to wixproj.

---

src/Installer/Bootstrapper/HearThis Bootstrap Installer.wixproj
src/Installer/Installer.wixproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/152)

Changed SignOutput back to True for release builds

---

src/HearThis/UI/UnitNavigationButton.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/153)

Horizontally center check marks

---

DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.fr.xlf
src/HearThis/Script/SampleScriptProvider.cs
src/HearThis/UI/ShiftClipsDlg.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/154)

Fix spelling error in string ID

---

src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/157)

HT-214: Fixed string display after setting UI locale

---

src/HearThis/UI/RecordingToolControl.Designer.cs
src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/158)

HT-214: Added missing unregister for HandleStringsLocalized

---

DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.fr.xlf
src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/ChooseProject.cs

Also improved wording of the Paratext 7 label in the Open Project dialog box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/160)

HT-356: Removed initial check for Paratext 7.

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/164)

HT-371: Added the missing System.ValueTuple.dll to the Installer

---

src/HearThis/UI/Shell.cs

Also only displays the release notes (if required) one the main window is visible and active.
Still not thrilled about the kludgy code, but at least now it behaves as desired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/166)

HT-370: Improved behavior for ensuring that HearThis comes up after launching from Installer

---

src/HearThis/Script/TextBundleScripture.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/169)

HT-375: Prevented load failure when a bundle's versification file doesn't have a name.

---

src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Properties/Settings.settings
src/HearThis/Script/IScripture.cs
src/HearThis/Script/IStyleInfoProvider.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/RepoMerger.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/Script/SkippedScriptLines.cs
src/HearThis/Script/StyleLookup.cs
src/HearThis/Script/TextBundleScripture.cs
src/HearThis/UI/ParatextScripture.cs
src/HearThis/UI/Shell.cs
src/HearThis/app.config
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/RepoMergerTests.cs
src/HearThisTests/ScriptProviderBaseTests.cs
src/HearThisTests/ScriptureStub.cs
src/HearThisTests/SentenceClauseSplitterTests.cs
src/HearThisTests/SkippedScriptLinesTests.cs

Changed certain styles that were previously unconditionally ignored to be skipped by default but available for recording if the user wants to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/168)

HT-374: Made it possible to record \io# paragraphs, etc.

---

src/HearThis/UI/AudioButtonsControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/171)

HT-377: Fixed deadlock caused by clicking button as playback is ending

---

HearThis.sln.DotSettings
src/HearThis/Script/IncompatibleProjectDataVersionException.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/Shell.cs

Improved data migration to save settings after each successful migration step to prevent repeating same migration.
Added check to prevent using older version of HearThis on a project whose data version is newer, which would likely be incompatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/173)

Data migration improvements

---

DistFiles/ReleaseNotes.md
src/HearThis/Script/MigrationProgressTracker.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/ScriptProviderBaseTests.cs

This involved refactoring of DoDataMigration to pull out testable method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/174)

HT-376: Added integration tests

---

HearThis.sln.DotSettings
src/HearThis/Script/ParatextProjectProxy.cs
src/HearThis/Script/Project.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/ExistingProjectsList.cs
src/HearThis/UI/ParatextScripture.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/175)

Added support for multiple Paratext projects with the same short name.

---

src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/176)

If user localizes main window title on the fly, it updates immediately

---

src/HearThis/HearThis.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/177)

HT-378: Upgraded to latest beta of L10nSharp in hopes of fixing IOException

---

DistFiles/aboutBox.htm
src/HearThis/HearThis.csproj
src/HearThis/Script/TextBundleScripture.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/TextBundleScriptureTests.cs

Also simplified the process of getting tokens for bundle-based projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/179)

Upgrade ParatextData and SIL/Microsoft packages

---

src/HearThis/HearThis.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/181)

Downgrade NAudio because turns out libraries are not compatible with 2.0

---

src/HearThis/Resources/usfm.sty
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/UI/BookButton.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ParserStateStub.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/usfm.sty

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/182)

Upgrade USFM.sty file

---

src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/184)

HT-366: Do not change script highlighting for skipped block

---

src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/ChapterRecordingInfoBase.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/DiscontiguousProgressTrackBar.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/ShiftClipsDlg.Designer.cs
src/HearThis/UI/ShiftClipsDlg.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/RepoMergerTests.cs
src/HearThisTests/ScriptProviderBaseTests.cs

Prevented treating right-click on DiscontiguousProgressTrackBar as a left click.
Changed HaveRecording to return false when the track bar is in the "Finished" state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/183)

HT-384: Prevent crash when clicking Shift Clicks menu and line is null.

---

src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/185)

HT-394: Added System.Memory.dll to Installer

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
DistFiles/localization/HearThis.pt.xlf
src/HearThis/UI/RecordingToolControl.cs

Made it so the Introduction label changes immediately when UI language changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/187)

Added new Portuguese translations and fixed minor I18n problem

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/ISkippedStyleInfoProvider.cs
src/HearThis/Script/MigrationProgressTracker.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ProjectOpenCancelledException.cs
src/HearThis/Script/RepoMerger.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/Script/SkippedScriptLines.cs
src/HearThis/UI/Shell.cs
src/HearThis/Utils/Utils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/189)

HT-398: Added checks when (de)serializing files so that errors would not be ignored

---

src/HearThis/Properties/Settings.Designer.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/190)

HT-398 [WIP]: Made version settings application-scoped so they would not be overridden by old user.config settings

---

src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThisTests/ChapterInfoTests.cs
src/HearThisTests/ClipRepositoryCharacterFilterTests.cs
src/HearThisTests/ClipRepositoryTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/197)

Detect and attempt to delete corrupt WAV files after recording and as part of export

---

src/HearThis/Script/ParatextParagraph.cs
src/HearThis/Script/ParatextScriptProvider.cs
src/HearThisTests/ParatextScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/198)

HT-410: Prevent treating verse text following mid-para chapter break as Heading styles

---

src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/AppPalette.cs
src/HearThis/UI/CustomButton.cs
src/HearThis/UI/DiscontiguousProgressTrackBar.cs
src/HearThis/UI/HearThisToolbarButton.cs
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/ScriptControl.cs
src/HearThis/UI/Shell.cs
src/HearThis/UI/ToolStripColorArrowRenderer.cs
src/HearThis/UI/UnitNavigationButton.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/199)

Fixed spelling error in AppPalette

---

src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.Designer.cs

by suspending layout of RecordingToolControl until initialization is complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/201)

HT-411: Fixed layout problem in some Asian versions of Windows

---

.nuget/NuGet.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/203)

Removed section from NuGet.targets that was outdated and no longer needed

---

DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.fr.xlf
DistFiles/localization/HearThis.pt.xlf
src/HearThis/UI/AudioButtonsControl.Designer.cs
src/HearThis/UI/AudioButtonsControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/207)

Fixed a discrepancy in the tooltip text for the record button.

---

src/HearThis/Utils/StringDifferences/StringDifferenceFinder.cs
src/HearThisTests/Utils/StringDifferences/StringDifferenceFinderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/215)

HT-259: Diff algorithm that favors whole-word comparison for isolating languages

---

src/HearThis/Script/ParatextScriptProvider.cs
src/HearThisTests/ParatextScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/216)

HT-420: Ignore (illegal) text following a chapter number

---

HearThis.sln.DotSettings
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.Designer.cs
src/HearThis/UI/ScriptControl.cs

Also made character labels for context lighter when recording
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/218)

HT-421: Fixed layout of RecordingToolControl so that bottom buttons are not too high

---

src/HearThis/UI/RecordInPartsDlg.cs
src/HearThisTests/app.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/217)

Code cleanup and fix to bindingRedirect in HearThisTests/app.config

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/SampleScriptProvider.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/Utils/Utils.cs
src/HearThis/app.config

Internationalized a hard-coded string in RecordInPartsDlg.
Fixed annoying message that displayed in Designer because of trying to set AudioButtonsControl.Path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/221)

Minor refactoring and code cleanup. Fix bug in Sample project.

---

DistFiles/ReleaseNotes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/224)

Removed duplicated text from Release Notes

---

src/HearThis/HearThis.csproj
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/MigrationProgressTracker.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/Script/SkippedScriptLines.cs
src/HearThisTests/HearThisTests.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/230)

HT-431: Changed to use SerializeToFileWithWriteThrough for writing XML files

---

src/HearThis/Communication/AndroidLink.cs
src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/Communication/IAndroidLink.cs
src/HearThis/Script/RepoMerger.cs

Rather than rethrowing the exception, offer to retry, ignore or abort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/233)

HT-227: Handle timeouts when syncing with Android more gracefully.

---

src/HearThis/Utils/StringDifferences/StringDifferenceFinder.cs

This prevents needless crash for user and hopefully enable us to get the needed info to debug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/238)

HT-441: Added code to detect error when computing string differences

---

build/build.proj
src/HearThis/HearThis.csproj
src/HearThis/app.config
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/app.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/239)

Updated Newtonsoft.Json and other libraries

---

src/HearThis/Publishing/ClipRepository.cs
src/HearThis/Publishing/PublishDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/240)

Bug fixes: HearThis continues publishing after user opts to fix errors; error when all files in chapter are invalid

---

src/HearThis/HearThis.csproj
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/243)

Switched from Hatton's DesktopAnalytics to SIL.DesktopAnalytics

---

HearThis.sln
HearThis.sln.DotSettings
build/build.proj
src/HearThis/HearThis.csproj
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/Utils/StringDifferences/StringDifferenceFinderTests.cs
src/Installer/Installer.wxs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/244)

Upgraded SIL Dlls and NUnit.ConsoleRunner

---

.gitignore
src/Installer/Bootstrapper/HearThis Bootstrap Installer.wxs
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/247)

HT-447: Fixed ICU version 70 loading problem

---

src/HearThis/HearThis.csproj
src/HearThis/Publishing/ClipRepository.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/Utils/StringDifferences/StringDifferenceFinderTests.cs
src/HearThisTests/app.config

- fix European decimal point problem
- add support for DBL metadata v. 2.2.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/248)

Upgraded SIL libraries

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/ParatextParagraph.cs
src/HearThis/Script/ScriptLine.cs
src/HearThisTests/ProjectTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/249)

Prevent NullReferenceException when updating display after deleting a clip

---

build/build.proj
src/Installer/template.download_info
src/template.releasenotes.download_info

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/250)

Added info about release notes so they can be published on website

---

src/HearThis/UI/AdministrativeSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/252)

Added Analytics to track whether users are using Scriptio Continua settings

---

src/HearThis/Communication/AndroidLink.cs
src/HearThis/HearThis.csproj
src/HearThis/UI/AndroidSyncDialog.Designer.cs
src/HearThis/UI/AndroidSyncDialog.resx

Fixes a bug that was causing sync timeouts, and changes some dialog wording and a link to be appropriate for a release version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/251)

Get HearThis ready for release of HT Android

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
build/build.proj
src/HearThis/Communication/AndroidLink.cs
src/HearThis/HearThis.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/253)

Prepare for release of v. 3.3 (to synchronize with HT Android 1.0)

---

HearThis.sln.DotSettings
src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/UI/AndroidSyncDialog.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

HT-372: Added try-catch to prevent unreproducible crash closing AndroidSyncDialog.
Added Analytics call to track syncs with Android.Android
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/254)

HT-452: Added code to prevent timing-related NullObjectReferenceException

---

DistFiles/ReleaseNotes.md
DistFiles/localization/.guidsForInstaller.xml
DistFiles/localization/HearThis.id.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/255)

Added Indonesian localization

---

HearThis.sln.DotSettings
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/ParatextParagraph.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/259)

Minor refactoring and corrections to comments

---

src/HearThis/HearThis.csproj
src/HearThis/Script/SentenceClauseSplitter.cs
src/HearThis/app.config
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/app.config
src/Installer/Installer.wxs

Also fixed a typo and removed some unnecessary parentheses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/258)

Upgraded to latest released version of SIL libraries.

---

src/HearThis/Script/ParatextScriptProvider.cs
src/HearThis/Script/ProjectSettings.cs
src/HearThis/Script/RangesToBreakByVerse.cs
src/HearThis/Script/ScriptureRange.cs
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/Script/RangesToBreakByVerseTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/260)

Added ability to selectively break text by verse rather than based on sentence-ending punctuation

---

src/HearThis/UI/SaveHearThisPackDlg.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/261)

HT-454: Prevent accessing null object to set the text of an invisible control

---

src/HearThis/HearThis.csproj
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.cs
src/Installer/Installer.wxs

Added missing file to Installer
Set Font on punctuation text boxes in admin AdministrativeSettings based on project font and zoom factor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/262)

Improvements to settings dialog

---

src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.cs

Tweaked design of AdministrativeSettings to keep text boxes from getting smaller than corresponding combo boxes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/263)

Changed to use Designer font size as basis instead of hard-coded 12.

---

src/HearThis/Script/ScriptProviderBase.cs

Changed the report to a more human-readable text file format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/264)

Prevent error caused by generating an illegal XML report.

---

build/TestInstallerBuild.bat
build/build.proj
src/template.releasenotes.download_info

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/269)

Added build target to convert release notes to HTML

---

src/HearThis/HearThis.csproj
src/HearThisTests/HearThisTests.csproj
src/Installer/Installer.wxs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/271)

Updated to latest version of DesktopAnalytics and several other libraries

---

DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.id.xlf
DistFiles/localization/HearThis.pt.xlf
DistFiles/localization/HearThis.vi.xlf
l10n/l10n.proj
src/HearThis/UI/AudioButtonsControl.Designer.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/RecordInPartsDlg.Designer.cs
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/272)

Fix keyboard shortcuts in record in parts dialog

---

DistFiles/localization/.guidsForInstaller.xml
src/Installer/Installer.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/273)

Added files to the Installer which are needed by new Analytics DLL

---

src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.resx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/275)

HT-194: Do not require user to click style checkbox twice to select/clear

---

src/HearThis/Script/Project.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/RecordingToolControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/276)

HT-468: Update slider to reflect newly skipped/unskipped styles

---

.gitignore
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/ChooseProject.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/280)

Minor refactoring/cleanup. Added Debug assertion for HT-470

---

DistFiles/localization/HearThis.es.xlf
src/HearThis/UI/AdministrativeSettings.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/288)

Updated a localization ID to be consistent and meaningful, and updated Spanish strings

---

DistFiles/localization/HearThis.id.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/289)

Updated Indonesian strings

---

DistFiles/ReleaseNotes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/292)

Added entry to release notes for v 3.5

---

DistFiles/localization/HearThis.es.xlf
src/HearThis/HearThis.csproj
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/ExistingProjectsList.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/app.config

[WIP] Need to upgrade to version 14.1.1 or later of SIL.Windows.Forms.DblBundle to get complete fix. (Depends on https://github.com/sillsdev/libpalaso/pull/1324)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/295)

HT-475 (HT-470): Replaced debug assertion with protective code.

---

DistFiles/localization/.guidsForInstaller.xml
HearThis.sln.DotSettings
build/build.proj
src/HearThis/HearThis.csproj
src/HearThis/Script/HearThisPackMaker.cs
src/HearThis/Script/HearThisPackReader.cs
src/HearThis/Script/ParserState.cs
src/HearThis/Script/TextBundleScripture.cs
src/HearThis/UI/ExistingProjectsList.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/BibleStatsTests.cs
src/HearThisTests/ChapterInfoTests.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/DiscontiguousProgressTrackBarTests.cs
src/HearThisTests/HearThisPackMakerTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/LinkLabelHelperTests.cs
src/HearThisTests/MegaVoicePublishingMethodTests.cs
src/HearThisTests/ParatextParagraphTests.cs
src/HearThisTests/ParatextScriptProviderTests.cs
src/HearThisTests/ProjectTests.cs
src/HearThisTests/PublishingModelTests.cs
src/HearThisTests/Script/ScriptureRangeTests.cs
src/HearThisTests/ScriptProviderBaseTests.cs
src/HearThisTests/ScriptureAppBuilderPublishingMethodTests.cs
src/HearThisTests/ScriptureStub.cs
src/HearThisTests/SentenceClauseSplitterTests.cs
src/HearThisTests/SkippedScriptLinesTests.cs
src/HearThisTests/TextBundleScriptureTests.cs
src/HearThisTests/app.config

Fixed problem loading versification for bundles with no metadata name set. Added logic to help user deal with case of trying to reopen a bundle when HT project exists Added/improved unit tests for HearThisPackMaker
Handled case when HearThisPack would get generated with no contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/300)

Upgraded DLLs, replacing deprecated use of DotNetZip with SharpZipLib

---

DistFiles/ReleaseNotes.md
DistFiles/aboutBox.htm
LICENSE.txt
src/HearThis/app.config
src/Installer/Installer.wxs

Added missing ICSharpCode.SharpZipLib.dll to installer and added binding redirect for System.Memory to app.config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/301)

Deployment fixes

---

src/HearThis/app.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/302)

Added binding redirect for System.Memory

---

DistFiles/ReleaseNotes.md
src/HearThis/Communication/AndroidSynchronization.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/304)

HT-222: HT Desktop now allows Android synch with wired network

---

src/HearThis/UI/ExistingProjectsList.designer.cs
src/Installer/Installer.wxs

HT-486: Made Type column read-only in Choose Project to avoid crash if user types something
Added missing installer file (that seems to have prevented analytics from working)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/308)

Fixed two problems

---

ReadMe.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/310)

Removed reference to outdated VS version

---

DistFiles/ReleaseNotes.md
DistFiles/localization/HearThis.es.xlf
HearThis.sln.DotSettings
src/HearThis/ExternalClipEditorInfo.cs
src/HearThis/UI/AdministrativeSettings.Designer.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/AdministrativeSettings.resx
src/HearThis/UI/ScriptTextHasChangedControl.Designer.cs
src/HearThis/UI/ScriptTextHasChangedControl.cs
src/HearThis/UI/Shell.cs
src/HearThisTests/ExternalClipEditorInfoTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/312)

HT-490: Added error handling code for attempting to open external editor

---

DistFiles/aboutBox.htm
build/build.proj

I had added this to another branch and didn't realize it was not in master when I did the 3.5.2 release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/315)

Added FileUpdate needed to set version and date in release notes

---

src/HearThis/Script/MultiVoiceBook.cs
src/HearThis/Script/MultiVoiceChapter.cs
src/HearThisTests/MultiVoiceScriptProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/317)

HT-493: Fixed index-out-of-range error caused by extra clip file(s)

---

DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.fr.xlf
DistFiles/localization/HearThis.id.xlf
DistFiles/localization/HearThis.pt.xlf
DistFiles/localization/HearThis.zh-CN.xlf
l10n/README.md
src/HearThis/HearThis.csproj
src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/ChooseProject.cs
src/HearThisTests/HearThisTests.csproj

Also upgraded to latest ParatextData DLL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/318)

Improved error message when installed/registered Paratext is not detected.

---

src/HearThis/FileContentionHelper.cs
src/HearThis/Program.cs
src/HearThis/Publishing/PublishingModel.cs
src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/MigrationProgressTracker.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/Script/SkippedScriptLines.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

We now retry up to 3 times and if it still fails, we wrap the exception to provide more info if there are other instances of HearThis running.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/323)

HT-499: Mitigate likelihood of XML read errors

---

src/HearThis/Script/ChapterInfo.cs
src/HearThis/Script/MultiVoiceScriptProvider.cs
src/HearThis/Script/Project.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/325)

HT-501: Added diagnostics to Analytics for NullReferenceException

---

build/build.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/326)

Added dependency on VersionNumbers to UpdateReleaseNotes build target

---

src/HearThis/HearThis.csproj
src/HearThis/app.config
src/HearThisTests/ChapterInfoTests.cs
src/HearThisTests/ClipRepositoryTests.cs
src/HearThisTests/HearThisPackMakerTests.cs
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/PublishingModelTests.cs
src/HearThisTests/app.config

Removed Microsoft.Windows.Compatibility, which was not actually needed or included in Installer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/327)

Upgraded SILL DLLs and other minor/patch versions of 3rd-party DLLs.

---

src/HearThis/UI/ChooseProject.Designer.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/331)

Show a wait cursor while the project chooser dialog is loading

---

DistFiles/aboutBox.htm
src/HearThis/HearThis.csproj
src/HearThisTests/HearThisTests.csproj
src/HearThisTests/app.config

The ultimate fix (part 2) requires some changes in libpalaso not yet completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/334)

HT-506: Added base target to aboutBox.htm and upgraded DLLs

---

DistFiles/localization/HearThis.az.xlf
DistFiles/localization/HearThis.es.xlf
DistFiles/localization/HearThis.fr.xlf
DistFiles/localization/HearThis.id.xlf
DistFiles/localization/HearThis.pt.xlf
DistFiles/localization/HearThis.vi.xlf
DistFiles/localization/HearThis.zh-CN.xlf
src/HearThis/Communication/AndroidSynchronization.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/DataMigrationReportNagDlg.Designer.cs
src/HearThis/UI/DataMigrationReportNagDlg.cs
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/Shell.cs

Need to update localized strings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/335)

HT-491: Improved error handling and analytics for recording problems

---

src/HearThis/ExternalClipEditorInfo.cs
src/HearThis/FileContentionHelper.cs
src/HearThis/Program.cs
src/HearThis/Publishing/PublishDialog.cs
src/HearThis/Publishing/PublishingModel.cs
src/HearThis/Script/Project.cs
src/HearThis/Script/ProjectSettings.cs
src/HearThis/Script/ScriptProviderBase.cs
src/HearThis/Script/SkippedScriptLines.cs
src/HearThis/UI/ActorCharacterChooser.cs
src/HearThis/UI/AdministrativeSettings.cs
src/HearThis/UI/AppPalette.cs
src/HearThis/UI/AudioButtonsControl.cs
src/HearThis/UI/ChooseProject.cs
src/HearThis/UI/RecordInPartsDlg.cs
src/HearThis/UI/RecordingToolControl.cs
src/HearThis/UI/ScriptControl.cs
src/HearThis/UI/SelectBundleDlg.cs
src/HearThis/UI/Shell.cs
src/HearThis/Utils/SafeSettings.cs

This class keeps track of vital settings and attempts disaster recovery if settings config file gets corrupted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/hearthis/332)

HT-503: Created SafeSettings class
